name: Deploy MkDocs to GitHub Pages

# Ejecutar el workflow cuando haya un push en la rama master
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del repositorio en la rama master
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: master

    # Paso 2: Instalar Python y MkDocs
    - name: Set up Python and Install MkDocs
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: |
        pip install mkdocs
        pip install mkdocs-material  # Si usas el tema Material para MkDocs

    # Paso 3: Build la documentaci√≥n con MkDocs
    - name: Build the documentation
      run: |
        mkdocs build

    # Paso 4: Desplegar en la rama gh-pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
